// This file was generated by prisma-field-encryption.

import type { PrismaClient, ctml_json } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = ctml_json['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'ctml_json',
    client,
    getTotalCount: client.ctml_json.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.ctml_json.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        data: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.ctml_json.update({
      where: {
        id: record.id
      },
      data: {
        data: record.data
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "data": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "version": {
 *       "modelName": "ctml_schema",
 *       "isList": false
 *     },
 *     "trial": {
 *       "modelName": "trial",
 *       "isList": false
 *     },
 *     "event": {
 *       "modelName": "event",
 *       "isList": true
 *     }
 *   }
 * }
 */
