#!/bin/bash

source ./vars.sh
echo "CTIMS_WEB_CONTAINER_IMAGE_LOCATION: $CTIMS_WEB_CONTAINER_IMAGE_LOCATION"
echo "GIT_REF: $GIT_REF"
echo "GIT_BRANCH: $GIT_BRANCH"
echo "GIT_BRANCH_SAFE: $GIT_BRANCH_SAFE"
echo "GIT_IS_CLEAN: $GIT_IS_CLEAN"
echo "COMMIT_ISH: $COMMIT_ISH"


echo "pushing ctims web with docker..."
docker push ${CTIMS_WEB_CONTAINER_IMAGE_LOCATION}:latest
docker push ${CTIMS_WEB_CONTAINER_IMAGE_LOCATION}:$GIT_REF
docker push ${CTIMS_WEB_CONTAINER_IMAGE_LOCATION}:$COMMIT_ISH
